version: '3.8'

services:
  app:
    build:
      context: ./..
      dockerfile: test_integration/Dockerfile
    container_name: test-rest-server
    ports:
      - "8081:8080"
    networks:
      - new_test
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:12
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1111
      - POSTGRES_DB=Avito
    ports:
      - "5434:5432"
    networks:
      - new_test
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d Avito" ]
      interval: 5s
      timeout: 5s
      retries: 10
    volumes:
      - ./../modelsql/up.sql:/docker-entrypoint-initdb.d/init.sql

networks:
  new_test: