name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.22'
      - name: Install dependencies
        run: go mod download
      - name: Build
        run: go build -v ./...

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.22'
      - name: Install dependencies
        run: go mod download
      - name: Test
        run: go test -v ./...

  deploy:
    needs: [build, test]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.22'
      - name: Install dependencies
        run: go mod download
      - name: Build
        run: go build -o myapp ./...
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Set up Docker Compose
        uses: docker/compose-action@v1
      - name: Deploy
        run: |
          # Здесь вы можете добавить команды для развертывания вашего приложения
          # Например, загрузка на сервер, развертывание в облаке и т.д.
          echo "Deploying application..."
