name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.22'
      - name: Install dependencies
        run: go mod download
      - name: Build
        run: go build -v ./...

#  test:
#    runs-on: ubuntu-latest
#    steps:
#      - name: Checkout code
#        uses: actions/checkout@v2
#      - name: Set up Go
#        uses: actions/setup-go@v2
#        with:
#          go-version: '1.22'
#      - name: Install dependencies
#        run: go mod download
#      - name: Set up Docker Buildx
#        uses: docker/setup-buildx-action@v1
#      - name: Set up Docker Compose
#        run: |
#          sudo curl -L "https://github.com/docker/compose/releases/download/$(curl -s https://api.github.com/repos/docker/compose/releases/latest | grep -Po '"tag_name": "\K.*?(?=")')/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
#          sudo chmod +x /usr/local/bin/docker-compose
#      - name: Test
#        run: go test -v ./...

  deploy:
    needs: [build, test]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.22'
      - name: Install dependencies
        run: go mod download
      - name: Build
        run: go build -o myapp ./cmd/app
      - name: Deploy
        run: |
          # Здесь вы можете добавить команды для развертывания вашего приложения
          # Например, загрузка на сервер, развертывание в облаке и т.д.
          echo "Deploying application..."
